version: '3.6'

services:
  db:
    hostname: db
    image: postgres
    ports:
      - "5432:5432"
  web:
    build: .
    command: bash startup-script.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
